Minor fix: adding variable to avoid DAG Import Errors on init
gestaogovbr/Ro-dou pull request #65
Opened 2023-09-05 23:54 UTC by leomarques90

![image](https://github.com/gestaogovbr/Ro-dou/assets/14188748/477d8a91-d5dd-4067-9579-f431cdfb819b)
Once we start the service a DAG Import Error appears because the variable `termos_exemplo_variavel` is not set.

I added it to the docker-compose with a value.

Thanks.

2023-09-06 14:01 UTC, vitorbellini commented
@leomarques90 obrigado pela contribuição. Você testou localmente se remove o erro? A princípio não deveria dar certo porque `termos_exemplo_variavel` é uma variável do Airflow, não de ambiente.. para adicionar uma variável no airflow pode ser por python ou cli dessa forma: https://airflow.apache.org/docs/apache-airflow/stable/cli-and-env-variables-ref.html#set_repeat1

2023-09-06 15:05 UTC, edulauer commented
> @leomarques90 obrigado pela contribuição. Você testou localmente se remove o erro? A princípio não deveria dar certo porque `termos_exemplo_variavel` é uma variável do Airflow, não de ambiente.. para adicionar uma variável no airflow pode ser por python ou cli dessa forma: https://airflow.apache.org/docs/apache-airflow/stable/cli-and-env-variables-ref.html#set_repeat1

Lembrando também que no Makefile já está previsto a criação da variável de teste pelo container do airflow. @leomarques90 você executou o comando make run no seu ambiente local?

2023-09-06 15:08 UTC, leomarques90 commented
> > @leomarques90 obrigado pela contribuição. Você testou localmente se remove o erro? A princípio não deveria dar certo porque `termos_exemplo_variavel` é uma variável do Airflow, não de ambiente.. para adicionar uma variável no airflow pode ser por python ou cli dessa forma: https://airflow.apache.org/docs/apache-airflow/stable/cli-and-env-variables-ref.html#set_repeat1
> 
> Lembrando também que no Makefile já está previsto a criação da variável de teste pelo container do airflow. @leomarques90 você executou o comando make run no seu ambiente local?

Olá, Edu, obrigado pela resposta.
SIm, executei `make run`, conforme a documentação.

2023-09-08 18:29 UTC, edulauer requested changes
AIRFLOW_VAR_TERMOS_VARIAVEL_EXEMPLO: 'exemplo'

2024-01-20 14:30 UTC, closed without merging